name: Deploy

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: write 

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, target: 'x86_64-pc-windows-msvc', suffix: '-win-x86_64' }
          - { os: macOS-11, target: 'x86_64-apple-darwin', suffix: '-mac-x86_64' }
          - { os: ubuntu-20.04, target: 'x86_64-unknown-linux-gnu', suffix: '-linux-x86_64' }
          - { os: ubuntu-20.04, target: 'x86_64-unknown-linux-musl', suffix: '-linux-muls-x86_64' }
          # - { os: windows-latest, target: 'arch64-pc-windows-msvc', suffix: '-linux-muls-arch64' }
          # - { os: macOS-11, target: 'aarch64-apple-darwin', suffix: '-mac-arch64' }
          # - { os: ubuntu-20.04, target: 'aarch64-unknown-linux-gnu', suffix: '-linux-arch64' }
          # - { os: ubuntu-20.04, target: 'aarch64-unknown-linux-musl', suffix: '-linux-musl-arch64' }

    steps:
    - name: Update Rust toolchain
      run: rustup update
    - name: Install cross
      run: cargo install cross 
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Zip archive
      run: |
        ls target/release/
        cp target/release/csv2dynamodb ./csv2dynamodb
        zip csv2dynamodb${{ matrix.config.suffix }}.zip csv2dynamodb

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          csv2dynamodb${{ matrix.config.suffix }}.zip
          LICENSE