name: Deploy

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions: write-all

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, target: 'x86_64-pc-windows-msvc', suffix: '-win-x86_64', extention: '.exe' }
          - { os: macOS-latest, target: 'x86_64-apple-darwin', suffix: '-mac-x86_64', extention: '' }
          - { os: ubuntu-latest, target: 'x86_64-unknown-linux-gnu', suffix: '-linux-x86_64', extention: '' }
          - { os: ubuntu-latest, target: 'x86_64-unknown-linux-musl', suffix: '-linux-muls-x86_64', extention: '' }
          # - { os: windows-latest, target: 'arch64-pc-windows-msvc', suffix: '-linux-win-arch64', extention: '.exe' }
          # - { os: macOS-11, target: 'aarch64-apple-darwin', suffix: '-mac-arch64', extention: '' }
          # - { os: ubuntu-latest, target: 'aarch64-unknown-linux-gnu', suffix: '-linux-arch64', extention: '' }
          # - { os: ubuntu-latest, target: 'aarch64-unknown-linux-musl', suffix: '-linux-musl-arch64', extention: '' }

    steps:
    - name: Update Rust toolchain
      run: rustup update
    - name: Install cross
      run: cargo install cross 
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release

    - name: Zip archive (Windows)
      if: matrix.config.os == 'windows-latest'
      run: |
        cp target/release/csv2dynamodb${{ matrix.config.extention }} ./csv2dynamodb${{ matrix.config.extention }}
        powershell Compress-Archive -Path ./csv2dynamodb${{ matrix.config.extention }} -DestinationPath csv2dynamodb${{ matrix.config.suffix }}.zip

    - name: Zip archive (not Windows)
      if: matrix.config.os != 'windows-latest'
      run: |
        cp target/release/csv2dynamodb${{ matrix.config.extention }} ./csv2dynamodb${{ matrix.config.extention }}
        zip csv2dynamodb${{ matrix.config.suffix }}.zip csv2dynamodb${{ matrix.config.extention }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          csv2dynamodb${{ matrix.config.suffix }}.zip
          LICENSE