name: Deploy

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, target: 'x86_64-pc-windows-msvc', suffix: '-win-x86_64' }
          - { os: macOS-11, target: 'x86_64-apple-darwin', suffix: '-mac-x86_64' }
          - { os: ubuntu-20.04, target: 'x86_64-unknown-linux-gnu', suffix: '-linux-x86_64' }
          - { os: ubuntu-20.04, target: 'x86_64-unknown-linux-musl', suffix: '-linux-muls-x86_64' }

    steps:
    - name: Update Rust toolchain
      run: rustup update
    - name: Install cross
      run: cargo install cross 
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Copy
      run: cp target/release/csv2dynamodb target/release/csv2dynamodb${{ matrix.config.suffix }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/release/csv2dynamodb${{ matrix.config.suffix }}
          LICENSE