name: E2E Test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Cargo.*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Cargo.*'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-slim
    outputs:
      table: ${{ steps.gen-table-name.outputs.table }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    
    - name: Install pnpm
      uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0

    - name: generate table name
      id: gen-table-name
      run: echo "table=csv2dynamodb-test-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: Create for testing table
      env:
        TABLE_NAME: ${{ steps.gen-table-name.outputs.table }}
      working-directory: tests/infra
      run: pnpm dlx aws-cdk@latest deploy -c name="${TABLE_NAME}" --require-approval=never

  test:
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Update Rust toolchain
      run: rustup update
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Run E2E test
      run: cargo run --verbose -- --file-path ./tests/test_data2.csv --table ${{ needs.setup.outputs.table }}

  tearDown:
    runs-on: ubuntu-slim
    needs: [setup, test]
    if: ${{ always() }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install pnpm
      uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: Remove for testing table
      env:
        TABLE_NAME: ${{ needs.setup.outputs.table }}
      working-directory: tests/infra
      run: pnpm dlx aws-cdk@latest destroy -c name="${TABLE_NAME}" -f
